@startuml

' skinparam backgroundColor #1e1e1e
' skinparam classBackgroundColor #2d2d2d
' skinparam classBorderColor White
' skinparam classFontColor White
' skinparam classAttributeIconColor White
' skinparam classArrowColor White
skinparam linetype ortho

package "Sean"{
    class Vector{

    }

    class UniquePtr{}

    class CharArray{}

    enum Direction{
        North
        South
        East
        West
    }

    enum ObjectType{
        Gold
        Weapon
        Armor
        Consumable
    }

    struct ParsedLocations{
        - mId : int
        - mExits : Direction[4]
        - mEnemies : Sean::Vector<Sean::CharArray>
        - mHiddenObjects : Sean::Vector<Sean::CharArray>
        - mVisibleObjects : Sean::Vector<Sean::CharArray>
        - mName : Sean::CharArray
        - mDescription : Sean::CharArray
    }
}


package "Backend"{

    class Location{
        + printShortDescription() : void
        + printLongDescription() : void
        + CreateEnemy(const char* aEnemy) : void
        + CreateVisibleGameObject(const char* aGameObject) : void
        + CreateHiddenGameObject(const char* aGameObject) : void

        - mNaam :char[]
        - mDescription : char[]
        - mVisibleObjects : Sean::Vector<GameObject>
        - mInVisibleObjects : Sean::Vector<GameObject>
        - mEnemies : Sean::Vector<Enemy>
        - mExits : &Location[]
    }


    class LocationFactory{
        +{static} CreateLocation(const char* alocation) : *Location
    }

    class GameObjectFactory{
        +{static} CreateGameObject(const char* aGameObject) : *GameObject
    }

    class EnemyFactory{
        +{static} CreateEnemy(const char* aEnemy) : *Enemy
    }

    class GameObject{
        -mName : char[]
        -mDescription : char[]
        -mType : ObjectType

        + printDescription() : void
    }

    class GoldObject{
        - mAmount : int
    }

    class WeaponObject{
        - mMinimumDamage : int
        - mMaximumDamage : int
    }

    class ArmorObject{
        - mArmor : int
    }

    class Enemy{
        - mHealth : int
        - mAttackPercentage : int
        - mHiddenObjects : Sean::Vector<GameObject>
        - mMinimumDamage : int
        - mMaximumDamage : int
    }

    class ConsumableObject{}

    class Dungeon{
        + Dungeon(&std::vector<ParsedLocations> aLocations) : void
        + Dungeon(int aLocations) : void

        + update() : void

        - mLocations : Sean::Vector<Location>
        - mCurrentLocation : &Location
    }

    class sqlReader{}

    Location o-- "Visible objects 0..*" GameObject
    Location o-- "Hidden Objects 0..*"GameObject

    Enemy o-- "Hidden Objects 0..*" GameObject

    GameObject <.. GameObjectFactory
    GameObject <.. EnemyFactory

    GameObject <|-- GoldObject
    GameObject <|-- WeaponObject
    GameObject <|-- ArmorObject
    GameObject <|-- ConsumableObject

    Dungeon o-- "0..*" Location
    Dungeon <-- LocationFactory

    Location <.. LocationFactory
    Location <-- GameObjectFactory
    Location <-- EnemyFactory

    GameObjectFactory <-- sqlReader
    EnemyFactory <-- sqlReader
    LocationFactory <-- sqlReader

}

package "Frontend"{

    class Player{
        - mHealth : int
        - mAttackPercentage : int
        - mGameObjects : std::vector<GameObjectFacade>>
        - mGold : int
        - mArmor : std::unique_ptr<ArmorObject>
        - mWeapon : std::unique_ptr<WeaponObject>
        - mGodMode : bool

        + printDescription() : void
        + equipWeapon(const char* aItem) : void
        + consumeConsumable(const char* aConsumable) : void
    }

    class Game{
        + run() : void
        - initialize() : void
        - loadDungeon(char *aPath) : void
        - generateDungeon() : void
        - playerInput() : void

        - mDungeonFacade : std::uniqueptr<DungeonFacade>
        - mCurrentLocation : &LocationFacade
    }

    class xmlReader{
        + xmlReader(char *aPath) : void
        + getLocations() : &std::vector<Sean::ParsedLocations>

        - mParsedLocations : std::vector<Sean::ParsedLocations>
    }

    Game o-- Player

    Game <-- xmlReader

}

' Misc
class DungeonFacade{
    - mDungeon : std::unique_ptr<Dungeon>

    + createDungeon(const &std::vector<Sean::ParsedLocations> aLocations) : void
    + generateDungeon(int aLocations) : void

    + printLongDescription() : void
    + printShortDescription() : void
    + moveHiddenObjects() : void
    + getGameObject(const char* aGameObject) : GameObject*
    + putGameObject(GameObject*) : bool
    + printGameObjectDescription(const char* aGameObject) : bool
    + printEnemyDescription(const char* aEnemy) : bool
    + moveLocation(Direction aDirection) : bool
    + attackEnemy(const char* aEnemy, &WeaponObject aWeapon) : bool
}

class GameObjectFacade{
    - mGameObject : std::unique_ptr<GameObject>

}

class GameObjectFactoryFacade{
    + createGameObject(std::string aObject) : void
}

class LocationFacade{
    - mLocation : &Location

    + getLocation : &Location
    + setLocation(&Location aLocation) : void
}


Game o-- "0..1" DungeonFacade

Player o-- "0..*" GameObjectFacade
Player <-- GameObjectFactoryFacade

GameObjectFactoryFacade <-- GameObjectFactory

DungeonFacade o--"0..1" Dungeon
GameObjectFacade o--"0..1" GameObject





@enduml